application: zoidbergmemes
version: 1
runtime: python
api_version: 1

handlers:

- url: /static
  expiration: "7d"
  static_dir: static

- url: /canvas-test
  static_dir: canvas-test

- url: /addTemplate
  script: landing.py

- url: /init
  script: init.py

- url: /initFix
  script: init.py

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  

- url:  /.*
  script: landing.py 
